### ISSUE TITLE
Remove CompositeWidget from interfaces

### ISSUE THREAD

**Issue by kitsonk** [dojo/interfaces#28]
Based on the CompositeWidget proposal, it will obsolece the need for the `CompositeWidget` interface in `WidgetBases`.

**Comment by agubler** [comment]
I don't think this needs removing, just adapting for the `d` proposal, initially `d` will only be supported for composite widgets (with the intention to extend this to simple and container widgets in the future).

Perhaps something like this:

```ts
export interface CompositeMixin {

	/**
	 * Array of functions that return children as DWrappers
	 */
	children: DWrapperFunction[];

	/**
	 * Accepts a DWrapper object and returns the approproate VNode
	 */
	getVNode(child: DWrapper): VNode;

	/**
	 * Prune empty children and manage them accordingly
	 */
	pruneChildren(): void;
}
```
