### ISSUE TITLE
Add interfaces for "d" function

### ISSUE THREAD

**Issue by kitsonk** [dojo/interfaces#29]
We need to create a set of interfaces which will provide the `d` function.  The `d` function will blend the ability to describe virtual DOM or widget factories for use within encapsulated composite widgets.

**Comment by agubler** [comment]
I think the `d` function will mainly be contained in widgets, there will be some shared interfaces and types that belong in this repository such as the wrappers.

usage of the function `d` will be from a static import much like Maquettes `h`
