### ISSUE TITLE
The registry interfaces have cross-cutting concerns and should be added

### ISSUE THREAD

**Issue by kitsonk** [dojo/interfaces#38]
It seems that the createable and identifiable registries have cross cutting concerns that form part of the foundations of Dojo 2 and should be included in the abilities interfaces.

On the other hand, the concept of the registry provider though, seems a bit of an implementation detail between app and widgets.

**Comment by agubler** [comment]
Closing as the enhancement that required these changes has been closed without merging dojo/widgets#105
